// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgMBi-Gb26JB6lJ9WRasXgIN6KMiv31Ts',
    appId: '1:413609360326:web:3f3b99b3c56ff60b1710c7',
    messagingSenderId: '413609360326',
    projectId: 'edulane-app',
    authDomain: 'edulane-app.firebaseapp.com',
    storageBucket: 'edulane-app.appspot.com',
    measurementId: 'G-M5CS4MZ5E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ6LHqP5cl4hemKpgGixh9X1j5k-C4_Us',
    appId: '1:413609360326:android:d9f9fe371e37edbe1710c7',
    messagingSenderId: '413609360326',
    projectId: 'edulane-app',
    storageBucket: 'edulane-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPWnjfBOpph8gExV0eNnHj2lCcyMyGEBw',
    appId: '1:413609360326:ios:2e0aa4e52e5a67491710c7',
    messagingSenderId: '413609360326',
    projectId: 'edulane-app',
    storageBucket: 'edulane-app.appspot.com',
    iosClientId: '413609360326-tsl07qasj65lbio11vvltckf50nvgqml.apps.googleusercontent.com',
    iosBundleId: 'com.example.edulane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPWnjfBOpph8gExV0eNnHj2lCcyMyGEBw',
    appId: '1:413609360326:ios:2e0aa4e52e5a67491710c7',
    messagingSenderId: '413609360326',
    projectId: 'edulane-app',
    storageBucket: 'edulane-app.appspot.com',
    iosClientId: '413609360326-tsl07qasj65lbio11vvltckf50nvgqml.apps.googleusercontent.com',
    iosBundleId: 'com.example.edulane',
  );
}
